AWSTemplateFormatVersion: "2010-09-09"
Description: Establishes supporting layers for Service Cloud Voice add-ons from AWS.
Parameters: 
  AWSRegion: 
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-west-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - eu-central-1
      - eu-west-2
    Description: The region code that you are deploying to. MAKE SURE that you have your console currently set to this region. Must be a region that supports Service Cloud Voice. 
Resources:
    SCVCommonPythonLayer:
        Type: AWS::Lambda::LayerVersion
        Properties: 
          CompatibleRuntimes: 
            - python3.8
          Content: 
            S3Bucket:
              !Join
                - ''
                - - 'scv-supporting-code-'
                  - !Ref AWSRegion
            S3Key: scv_common_layer/scv_python_common.zip
          Description: Provides dependencies code and functions for Python Lambda functions that augment the Service Cloud Voice offering from Salesforce
          LayerName: aws_scvhelper_common_python
          LicenseInfo: https://opensource.org/licenses/MIT
    SCVCommonNodeLayer:
        Type: AWS::Lambda::LayerVersion
        Properties: 
          CompatibleRuntimes: 
            - nodejs12.x
          Content: 
            S3Bucket:
              !Join
                - ''
                - - 'scv-supporting-code-'
                  - !Ref AWSRegion
            S3Key: scv_common_layer/scv_node_common.zip
          Description: Provides dependencies code and functions for node.js Lambda functions that augment the Service Cloud Voice offering from Salesforce
          LayerName: aws_scvhelper_common_node
          LicenseInfo: https://opensource.org/licenses/MIT
Outputs:
  SCVCommonPythonLayerARN:
    Description: ARN for the Python common layer
    Value: !Ref SCVCommonPythonLayer
  SCVCommonNodeLayerARN:
    Description: ARN for the node.js common layer
    Value: !Ref SCVCommonNodeLayer  