
AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the AWS Lambda functions required to enable the Data-Directed Routing: Flow Routing examples.
Parameters:
    AWSRegion:
        Type: String
        Default: us-east-1
        AllowedValues:
          - us-east-1
          - us-west-2
          - ap-southeast-1
          - ap-southeast-2
          - ap-northeast-1
          - eu-central-1
          - eu-west-2
        Description: The region code that you are deploying to. This should be the same region that your Amazon Connect instance is deployed to. MAKE SURE that you have your console currently set to this region.
    ConnectInstanceName:
        Type: String
        Default: REPLACEME
        Description: Provide the instance name for Amazon Connect.
    AWSSCVCommonRole:
        Type: String
        Default: REPLACEME
        Description: ARN of the awsscv_common_role role
    AWSSCVCommonLambdaPythonLayer:
        Type: String
        Default: REPLACEME
        Description: ARN of the common python layer
    sfConfig:
        Type: String
        Default: REPLACEME
        Description: ARN for your Salesforce config in AWS Secrets Manager.
    sfOrgId:
        Type: String
        Default: REPLACEME
        Description: Provide the ID for your Salesforce Org
    sfQueuePrefix:
        Type: String
        Default: QQ
        Description: The prefix used for Salesforce Queues. The default is QQ.
Resources:
    awsscvddrflow:
        Type: AWS::Lambda::Function
        Properties:
          Code:
           S3Bucket:
              !Join
                - ''
                - - 'awsscv-supporting-code-'
                  - !Ref AWSRegion
           S3Key: cf_code/awsscv_ddr_flow.py.zip
          Description: Uses Salesforce REST API to invoke a flow and receive a response.
          Environment:
            Variables:
              sf_org_id:
                Ref: sfOrgId
              queue_prefix:
                Ref: sfQueuePrefix
              sf_config_sm_arn:
                Ref: sfConfig
          FunctionName:
            !Join
                - ''
                - - 'awsscv_ddr_flow_'
                  - !Ref ConnectInstanceName
          Handler: awsscv_ddr_flow.lambda_handler
          Layers: [!Ref AWSSCVCommonLambdaPythonLayer]
          Role: !Ref AWSSCVCommonRole
          Runtime: python3.8
          Timeout: 8
    awsscvddrflowtargetprocessor:
        Type: AWS::Lambda::Function
        Properties:
          Code:
           S3Bucket:
              !Join
                - ''
                - - 'awsscv-supporting-code-'
                  - !Ref AWSRegion
           S3Key: cf_code/awsscv_ddr_flow_target_processor.py.zip
          Description: Processes the targets in a DDR Flow setup
          FunctionName:
            !Join
                - ''
                - - 'awsscv_ddr_flow_target_processor_'
                  - !Ref ConnectInstanceName
          Handler: awsscv_ddr_flow_target_processor.lambda_handler
          Layers: [!Ref AWSSCVCommonLambdaPythonLayer]
          Role: !Ref AWSSCVCommonRole
          Runtime: python3.8
          Timeout: 8
